version: '3.1'

services:
  database:
    image: mysql:5.7.34
    environment:
      MYSQL_ROOT_PASSWORD: 'root123'
      MYSQL_PASSWORD: 'root123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
